# Generated by Django 5.2 on 2025-05-02 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasktrek', '0004_alter_employee_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='username',
            field=models.CharField(default='nousername', max_length=64),
        ),
    ]
