# Generated by Django 5.2 on 2025-05-07 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasktrek', '0005_employee_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_team',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='name',
            field=models.CharField(default='...', max_length=32),
        ),
    ]
