# Generated by Django 5.2 on 2025-05-08 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasktrek', '0006_task_is_team_task_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='status',
        ),
        migrations.AddField(
            model_name='task',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
    ]
