# Generated by Django 5.2 on 2025-05-09 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasktrek', '0007_remove_task_status_task_is_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.CharField(default=''),
        ),
    ]
