# Generated by Django 5.2 on 2025-05-09 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasktrek', '0009_alter_task_is_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='is_team',
            field=models.CharField(default='False'),
        ),
    ]
